SECURITY.md: make the process more concrete
lima-vm/.github pull request #8
Opened 2024-06-11 20:14 UTC by AkihiroSuda

2024-06-11 22:47 UTC, jandubois requested changes
There is a typo.

It is also not clear how the reporter can identify committers on Slack. I think we mostly have similar Slack and GitHub usernames, but that cannot be guaranteed. Do we need to list our CNCF Slack usernames explicitly in the maintainers document?

2024-06-11 22:47 UTC, jandubois commented on SECURITY.md
> +If you do not see any response after 7 days, ping the Commiters via email or [Slack](https://lima-vm.io/docs/community/) privately.
```suggestion
If you do not see any response after 7 days, ping the Committers via email or [Slack](https://lima-vm.io/docs/community/) privately.
```

2024-06-11 22:50 UTC, jandubois commented
> Do we need to list our CNCF Slack usernames explicitly in the maintainers document?

Oops, I just realized that we can be found by our regular names, not handles, so this should be good enough.

2024-06-12 04:36 UTC, AkihiroSuda commented on SECURITY.md
> +If you do not see any response after 7 days, ping the Commiters via email or [Slack](https://lima-vm.io/docs/community/) privately.
fixed

2024-06-12 04:55 UTC, jandubois approved these changes
Thanks, LGTM

2024-06-12 04:55 UTC, merged